#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-only
"""Embed the report assets without adding a runtime file dependency."""
import json
import sys
from pathlib import Path


output = Path(sys.argv[1])
parts = ['/* Generated by scripts/embed-assets.py; edit the source assets */\n']
for name in sys.argv[2:]:
    path = Path(name)
    symbol = path.name.replace('.', '_').replace('-', '_')
    parts.append(f'static const char {symbol}[] =\n')
    parts.extend(json.dumps(line) + '\n' for line in path.read_text(encoding='utf-8').splitlines(True))
    parts.append(';\n')

output.parent.mkdir(parents=True, exist_ok=True)

# Keep an interrupted build from leaving a partial generated header
temporary = output.with_suffix('.tmp')
temporary.write_text(''.join(parts), encoding='utf-8')
temporary.replace(output)
