#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""Embed the report assets without adding a runtime file dependency."""
import base64
import hashlib
import json
import sys
from pathlib import Path


output = Path(sys.argv[1])
parts = ['/* Generated by scripts/embed-assets.py; edit the source assets */\n']
for name in sys.argv[2:]:
    path = Path(name)
    symbol = path.name.lower().replace('.', '_').replace('-', '_')
    contents = path.read_text(encoding='utf-8')
    parts.append(f'static const char {symbol}[] =\n')
    parts.extend(json.dumps(line) + '\n' for line in contents.splitlines(True))
    parts.append(';\n')
    if path.suffix == '.js':
        # The renderer puts a newline between the opening tag and the asset
        digest = hashlib.sha256(('\n' + contents).encode('utf-8')).digest()
        encoded = base64.b64encode(digest).decode('ascii')
        parts.append(f'static const char {symbol}_hash[] = "sha256-{encoded}";\n')

output.parent.mkdir(parents=True, exist_ok=True)

# Keep an interrupted build from leaving a partial generated header
temporary = output.with_suffix('.tmp')
temporary.write_text(''.join(parts), encoding='utf-8')
temporary.replace(output)
